databases:
  - name: rails_test_db
    databaseName: rails_test_db
    user: rails_test_db_user
    region: singapore

services:
  - type: web
    name: rails test
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_test_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

