databases:
  - name: rails_test_db
    databaseName: rails_test_db
    user: rails_test_db_user
    region: singapore

services:
  - type: web
    name: rails_test_db
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: render_app
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false